const main = document.createElement("div");
const firstNameDiv = document.createElement("div");
const firstName = document.createElement("p");
firstName.innerHTML = "firstName";
const firstNameInput = document.createElement("input");
firstNameDiv.style.display = "flex";
firstNameDiv.appendChild(firstNameInput);
firstNameDiv.appendChild(firstName);
main.appendChild(firstNameDiv);
const lastNameDiv = document.createElement("div");
const lastName = document.createElement("p");
lastName.innerHTML = "lastName";
const lastNameInput = document.createElement("input");
lastNameDiv.style.display = "flex";
lastNameDiv.appendChild(larstNameInput);
lastNameDiv.appendChild(lastName);
main.appendChild(lastNameDiv);
document.getElementById(form).appendChild(main);
